### PR TITLE
WIP: New Landing Page

### PR DESCRIPTION
**Pull request by vinaypuppal**
# Modified landing-page according to mockup in https://github.com/coderplex/coderplex/issues/41#issuecomment-343732914

- [Desktop screnshot](https://user-images.githubusercontent.com/8843216/32706295-761a0670-c842-11e7-882c-5b743ba132bd.png)

- [Mobile_ nexus 5x](https://user-images.githubusercontent.com/8843216/32706303-974c95b0-c842-11e7-9af7-2eb7d284b02a.png)

@M-ZubairAhmed **Notice base branch its `devlop`. From now on all new changes regarding UI will go into this branch and once we complete migration we will merge `devlop` into `master`.**

### CODE REVIEW

**Comment by buoyantair** [comment]
This is very nice!

**Comment by vinaypuppal** [comment]
@buoyantair Thanks, these are helpful.

**Comment by vinaypuppal** [comment]
@saiabhijitht 
As per you suggestions from https://github.com/coderplex/coderplex/issues/41#issuecomment-343859926
> Preview https://deploy-preview-106--coderplex.netlify.com
- [x] Set the global border radius to 0px for now. For all learn cards, event cards and buttons.
- [x] Buttons shall be sized as small, medium and Large.
     - Small for Sign/Signup.(3/8th height of Large buttons)
    - Medium for CTA buttons and subscribe(Half the height of large buttons)
    - Large for Join Discord.(The present height of Discord button is good)
     > Once you verify
- Card design:
    - [x] Image background: #FFF;
    - [x] Title bg: #F6F6F6;
    - [x] Stroke: #B9B9B9;
    - [x] Section bg: #F6F6F6;
- Header:
    - [x] Set Height to 60px.

- [ ] Reduce the gap between the nav items 
     > The current gap is calucalted dynamically using flexbox reducing the size is ruining the `Login` button width.
- [ ] and add Home section. 
  > No need of `Home` link i think because clicking on `Logo` is taking back to home

**Comment by pbteja1998** [comment]
"Learn more about Hacker Space" in index page is linked to "/learn" instead of "/space"

**Comment by duttakapil** [comment]
Found a typo : "Join our Discord Server, and say "Hello, **word**!" > should be `world`

**Comment by duttakapil** [comment]
Super minor edit : `S` in Open Source in the "Offline Co-learning Space" description should be capital

**Comment by pbteja1998** [comment]
Another typo in index page under events section 
`collabration` - - > `collaboration`

**Comment by saiabhijitht** [comment]
1. Banner Background img is not the same as given in assets.
2. Remove the curve for the Open source learning guides section background.
3. Top and bottom padding for "Our guides are crowd-sourced recommendations of free online resources to learn any technology" shall be equal. Reduce the padding-bottom for it.
4. buttons:
- Let all buttons in the page be same size, except Signin button in nav bar.
- In white buttons, make the font color complete black.
- On Hover for all buttons: button bg = #340080
	text color = #fff
5. Footer(For this version):
- Reduce the text as "We are constantly updating our platform. <br>Do subscribe to stay informed."
- Remove the border radius of the Email address input and use the same button we used till now for subscribe also.
- Remove the Youtube and Instagram icons. Youtube will confuse people when they see FCC channel.

**Comment by duttakapil** [comment]
Correction : YouTube should be linked to [Coderplex Community](https://www.youtube.com/channel/UCTkguToherUvVNnzMFINk-w) channel. 

And Instagram link should still be there. The profile will need to be updated with a lot of pictures from our meetups / events

**Comment by vinaypuppal** [comment]
Closed due to #107

**Pull request closed without merging**
