### PR TITLE
Allow Nested Learn Guides

### PR DESCRIPTION
**Pull request by pbteja1998**
- Added Nested Accordion for showing learn guides.

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
please provide description to help us figure out all changes without going through changes.

**Comment by pbteja1998** [comment]
I thought the title is self-explanatory. Check guide section of https://deploy-preview-65--coderplex.netlify.com/learn/laravel/   to see the changes in the Laravel guide.

**Comment by M-ZubairAhmed** [comment]
the only reason we didn't work with this nesting is because on mobile it become too narrow. And we we plan to not show curriculum details in the current page but we take it to another page. The design of that page is still open to discussion you. Can you help us with that too.

**Comment by pbteja1998** [comment]
So, in `learn/subject` page, there will only be titles of chapters then? Why can't we have two designs one for mobile and other for computer?

**Comment by M-ZubairAhmed** [comment]
let's discuss it here https://github.com/coderplex/coderplex/issues/66 I hope you don't mind as it will bring other people's idea on board

**Comment by duttakapil** [comment]
I don't mind this nesting on desktop version for the immediate future. Of course, the direction we need to go is taking the user to a new page with a left-hand and right-hand interface for learning. But for now, this is actually fine

**Comment by pbteja1998** [comment]
No, it's looks like that sometimes. But it's something kinda caching issue, I guess but not sure why it's happening. But you can go to the overview and contributors section even after expanding guide.

**Comment by buoyantair** [comment]
Do it like discord, use the accordian to the left to show all the table of contents, and load the data to the right side... 

on mobile, only show the data, and the accordian transforms into a responsive menu

**Pull request closed without merging**
