### PR TITLE
v2-alpha release

### PR DESCRIPTION
**Pull request by M-ZubairAhmed**

### CODE REVIEW

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed 
Why now?
> I thought we will release this once login and profile functionality is done

**Comment by M-ZubairAhmed** [comment]
kapil wants it now, because of the competition

**Comment by M-ZubairAhmed** [comment]
i cannot push to develop.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed Try now

**Pull request merged**
