### PR TITLE
Z-index glitch

### PR DESCRIPTION
**Pull request by buoyantair**
On several pages, components that appear/animate to "rise" seem to overlap the header component. 
I've added a z-index definition to push the header component to the highest layer so that no other component overlaps / shadows it.
image
image
image

### CODE REVIEW

**Comment by vinaypuppal** [comment]
@buoyantair Thanks

**Comment by buoyantair** [comment]
@vinaypuppal Doesn't seem to be fixed is it?

**Comment by vinaypuppal** [comment]
@buoyantair It seems fixed to me
screen shot 2017-10-20 at 22 21 56

**Comment by buoyantair** [comment]
@vinaypuppal Okay!

**Pull request merged**
