### PR TITLE
New design and migration to emotion(css-in-js)

### PR DESCRIPTION
**Pull request by vinaypuppal**
###  Removed `semantic-ui-react` as dependency and migrated css to [emotion](https://emotion.sh) a `css-in-js` library for Reactjs
- Landing page is visually same as in #106 
- Space page is updated with new UI
- And other pages are in WIP

Check below preview url for demo.

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
should i add styling to events and learn in this pr or make another one?

**Comment by vinaypuppal** [comment]
@saiabhijitht From your suggestion https://github.com/coderplex/coderplex/pull/106#issuecomment-344344017 
- [ ] Banner Background img is not the same as given in assets.
   > I did not modify this: I feel your pattern image does not sync with theme of the site because it has `browsers` `404` ...etc icons. I like the present pattern image, if you got any other ideas let me know we can change it.
- [x] Remove the curve for the Open source learning guides section background.
- [x] Top and bottom padding for "Our guides are crowd-sourced recommendations of free online resources to learn any technology" shall be equal. Reduce the padding-bottom for it.
   > I modified it but not sure if its what you want once verify and let me know.

### Buttons
- [x] Let all buttons in the page be same size, except Signin button in nav bar.
- [x] In white buttons, make the font color complete black.
- [] On Hover for all buttons: button bg = `#340080`, text color = `#ffffff`
   > This colors does not look good to me, so I used `#6f19ed` as hover `background-color`, `#ffffff` as text color  on coloured buttons and `#eeeeee` as hover `background-color`, `#222222` as text color  on white buttons .

### Footer(For this version):
- [x] Reduce the text as "We are constantly updating our platform. Do subscribe to stay informed."
- [x] Remove the border radius of the Email address input and use the same button we used till now for subscribe also.
- [ ] Remove the Youtube and Instagram icons. Youtube will confuse people when they see FCC channel.

**Comment by saiabhijitht** [comment]
Learn Card on Hover:

Remove the transform sizing

- [ ] Card Border color: #000;

- [ ] Text background: #3c3c3c;

- [ ] Text color: #FFF;

**Comment by vinaypuppal** [comment]
@saiabhijitht Can you also specify the reason to remove `scaling` card oh hover.

**Comment by saiabhijitht** [comment]
@vinaypuppal  
I am trying to make all elements consistent to each other. 
Drop shadows might go well with many landing pages which are used for marketing purpose. But applications are always good in 2 dimension. So I am asking to remove drop shadows. 
And transform makes us trick that they are coming out of the plane. So I am avoiding it also.

It would all make sense when I give you the style sheet where all elements would be represented.
I actually thought the process would go through lean management and pushed that task to the end. But we are going through agile methodology, where we are designing and developing in parallel. I should have given the style sheet before so we would all be on same pace. Let us plan it for the next version of release.

**Comment by M-ZubairAhmed** [comment]
@vinaypuppal we are getting .vscode files in the repo although its its gitignore. can you remove it from the repo and keep in your end if you are using vscode

**Comment by vinaypuppal** [comment]
@saiabhijitht Thanks for the explanation. 

---

@M-ZubairAhmed can you also make changes suggested above along with what you are working now.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed `.vscode` contains config settings which is required for this project. So no harm in committing them to GitHub.

**Comment by M-ZubairAhmed** [comment]
@vinaypuppal i dont use vscode is it still required for my local copy?

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed If others use `vscode` then it will be useful https://stackoverflow.com/questions/32964920/should-i-commit-the-vscode-folder-to-source-control 
Both `.vscode` settings and `jsconfig.json` helps to provide css syntax highlighting and autocompletion when writing css with `emotion`.  I will add code editor section about `vscode` and plugins which will make development workflow easy for our project in coming days.

**Comment by vinaypuppal** [comment]
I can remove these and suggest these settings in contributing file. What do you say?

**Comment by M-ZubairAhmed** [comment]
@saiabhijitht 
> Remove the transform sizing
how would you like it to react on hover?

**Comment by saiabhijitht** [comment]
@M-ZubairAhmed 
On Hover: These are different from the present card values.
Card Border color: #000;
Text background: #3c3c3c;
Text color: #FFF;

**Comment by M-ZubairAhmed** [comment]
now working on events cards. Probably we should change the heading of this pr?

**Comment by vinaypuppal** [comment]
@saiabhijitht Do you have any other suggestions/changes for landing page?
If not @M-ZubairAhmed lets merge this PR and you can open new PR's for other page updates.

**Comment by M-ZubairAhmed** [comment]
sure please go ahead, I have not committed my latest changes.

**Comment by duttakapil** [comment]
I would suggest we keep the `Price` section in the same format on the /space page :
image

The pink color could be changed to the blue put forward by @saiabhijitht 

Also, did we add `the best` before the word `free` under the "Open Source Learning Guides" heading on our landing page?

**Comment by M-ZubairAhmed** [comment]
yes Kapil we shall edit as per your suggestion.

**Comment by pbteja1998** [comment]
`JOIN DISCORD` button in home page is not working (in [this](https://deploy-preview-107--coderplex.netlify.com))

**Comment by duttakapil** [comment]
Seems to be working for me @pbteja1998

**Comment by duttakapil** [comment]
However, the learning guides are not showing up in the demo site. Even the Laravel guide is showing "Coming soon". And the Events page as well, it's showing loading under past events

**Comment by M-ZubairAhmed** [comment]
we recently migrated away from semantic UI, we are writing everything from scratch. Request everybody to review the items which are completed.

**Comment by buoyantair** [comment]
@M-ZubairAhmed What made you take a stand away from semantic-ui ?

**Comment by pbteja1998** [comment]
@duttakapil yeah, @vinaypuppal fixed the link in discord button in recent commit. It was not working before.

**Comment by vinaypuppal** [comment]
@duttakapil Ref: https://github.com/coderplex/coderplex/pull/107#issuecomment-345495014
 Can you use github review system to pinpoint change when you want to request some changes rather than explaining them in text.

**Comment by vinaypuppal** [comment]
Merging this PR. For any changes open new issues mentioning `develop` branch.

**Comment by vinaypuppal** [comment]
BTW `develop` branch site is accessible at https://dev.coderplex.org

**Pull request merged**
