### PR TITLE
Navbar is now responsive

### PR DESCRIPTION
**Pull request by buoyantair**
- Transformed Header Component to be a class.
- Made the Navbar responsive.

and also
- Don't use padding in CSS, because it is not quite responsive.

### CODE REVIEW

**Comment by M-ZubairAhmed** [comment]
@buoyantair amazing, i was procrastinating this for a while now. thanks for bring this up here in form of pr.

**Comment by buoyantair** [comment]
@M-ZubairAhmed You were searching for Issues on `facebook/react` xD :D  
I also didn't get time to work on this since I said @duttakapil that I'd work on it,
Anyways, the menu at this point is not smooth, aka there's no transitions etc. and Also the menu is super deep in the tree and with flex box, things get messy in such cases. I'll try to tweak it next time.

**Comment by M-ZubairAhmed** [comment]
@buoyantair yes it does needs tweaking a bit, Also i was thinking we could move the hamburger on the left and logo in middle. Could you do that while you are at it.

**Comment by buoyantair** [comment]
@M-ZubairAhmed Yeah will def do that when I tweak them the next time (probably this night idk)

**Comment by M-ZubairAhmed** [comment]
@buoyantair change of plans, we want to chuck of the current menu and replace it with semantic-ui menu in web and in mobile we would like to have semantic-ui sidebar instead. We are on a time constraint here, can you implement it by today, if not its ok i will complete it off

**Comment by buoyantair** [comment]
@M-ZubairAhmed Im busy today, you might wanna take off if theres a time constraint

**Comment by M-ZubairAhmed** [comment]
thank you @buoyantair

**Comment by buoyantair** [comment]
@M-ZubairAhmed Im busy today, you might wanna take off if theres a time constraint

**Pull request closed without merging**
