### PR TITLE
#37 multiline span on landing page in events card

### PR DESCRIPTION
**Pull request by abiduzz420**

### CODE REVIEW

**Comment by abiduzz420** [comment]
I have added logic for selective multi-line using prop. For the RowEvent component on landing page, isMutliLine set to true is passed.

**Comment by M-ZubairAhmed** [comment]
thanks thats great work. Please do checkout issues space from time to time.
Please start us to receive updates

**Comment by abiduzz420** [comment]
Formatting changes got included in the earlier commit for package.json and package-lock.json. I have not added any additional dependency.

**Comment by M-ZubairAhmed** [comment]
@abiduzz420 yes I have accepted, but its generally a good practice to only include the files which you have worked on in the pr.

**Pull request merged**
